name: peminjam_perpustakaan_kelas_b
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: 2.0.3
  intl: 0.19.0
  get: 4.6.5
  flutter_svg: ^2.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

#flutter:
#  assets:
#    - assets/images/
#
#  uses-material-design: true
#
#
#
#  fonts:
#    - family: Poopins
#      fonts:
#        - asset: assets/fonts/Poppins-Bold.ttf
#        - asset: assets/fonts/Poppins-Italic.ttf
#        - asset: assets/fonts/Poppins-Medium.ttf
#        - asset: assets/fonts/Poppins-Regular.ttf

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poopins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf